Queue/M-739-DailyTemperatures/SongI.java
Tree/E-226-InvertBinaryTree/SongI.java
Tree/M-102-BinaryTree LevelOrderTraversal/Songi.java

'226. Invert Binary Tree
https://www.notion.so/easy-fab495483d68413db77656a4db366e2b
'739. Daily Temperatures, 
'102. Binary Tree Level Order Traversal
https://www.notion.so/medium-c8e2cbb25f6b481eb7103e908dda3e8c

[SongI] Queue, Tree 문제 풀이

---

Tree/M-102-BinaryTree LevelOrderTraversal/JeongYe.java

- 트리 레벨, 레벨 별 노드 값 목록을 저장하는 Map 생성 
- root -> left -> right 방향으로 순회 
- 트리 한 단계 타고 내려갈때마다 `depth`를 증가 시키고, 다시 올라올때 `depth` 감소 
https://www.notion.so/Binary-Tree-Level-Order-Traversal-LeetCode-6890667fa4f04a1eacadc71cd0c6761d

102. Binary Tree Level Order Traversal 풀이

---

Permutation&Combination/M-46-Permutations/SongI.java

순열 문제 
원하는 형식이 리스트의 리스트 여서 당황했다.
기존에 순열문제를 푸는 방식으로 풀었는데 리스트 참조할때 new 로 할당하지 않아서 바뀌는 값에 영향을 받아
제대로 답이 구해지지 않아 애 먹었다...

[SONGI]46. Permutations 문제 풀이

---

Permutation&Combination/M-46-Permutations/JeongYe.java

저는 swap을 이용해서 풀었습니다! 
순열 문제 많이 안풀어봐서 아직 낯서네요ㅠ_ㅠ

46. Permutations 풀이

---

Permutation&Combination/M-46-Permutations/YoRim.cpp

46.Permutations 풀이

---

DP/M-931-Minimum Falling Path Sum/YoRim.cpp

1. matrix[i][j] -> i=0, j=0부터 i=0, j=matrix[0].size()까지 dp에 넣어준다.
2. i=1 부터 2중 for 문을 사용하여 dp로 푼다.
3. dp 의 가장 마지막 행에서 최소값을 찾는다.

931. Minimum Falling Path sum 문제 풀이

---

DP/M-931-Minimum Falling Path Sum/SongI.java

DP 문제
다음 줄로 넘어갈 때 마다 최솟값을 더해준다.

[SongI] 931 minFallingPathSum 풀이

---

Tree/M-230-Kth Smallest Element in a BST/JeongYe.js

저는 두가지 방법으로 풀었습니다! 
첫 번째 시도는 BST에서 루트 보다 작은 노드는 왼쪽 트리에, 큰 노드는 오른쪽 트리에 존재한다는 점을 이용해서 `left -> root -> right` 순으로 탐색하면서 오름차 순으로 정렬된 배열을 이용하여서 풀었습니다. 
근데 이렇게 풀면 k번째 노드를 찾기 위해서 모든 노드를 탐색해야 하는 단점이 있어서 불필요한 탐색을 줄일 수 있는 방법을 생각해 보았습니다😭
두 번째 풀이는 다른 분 꺼 참고해서 풀었습니다! 
- K번째 노드를 저장할 target 변수를 생성한다. 
- 노드를 탐색 할 때 마다 K를 1씩 감소 시킨다. 
- K가 0이 되면 현재 노드를 target에 넣어서 리턴 한다.

[JeongYe] 230. Kth Smallest Element in a BST 풀이 

---

Tree/M-230-Kth Smallest Element in a BST/SongI.java

이진탐색트리는 작은수 (왼쪽노드) -> 그다음큰수 (루트) -> 큰수(오른쪽노드) 의 순서대로 놓여집니다.
이 순서를 보면 트리 순회 방법 중 하나인 중위 순회 순서와 같습니다.
중위 순회를 돌면서 k번째 작은 수를 찾을 수 있습니다.

[SongI] 230. Kth Smallest Element in a BST 풀이

---

Tree/YoRim.cpp

left -> root -> right 중위 순회를 사용하여 k--를 하며 답을 구했습니다.

230. Kth Smallest Element in a BST 풀이

---

Permutation&Combination/M-39-Combination Sum/SongI.java

합이 target이 되는 모임을 뽑아내는 문제 (순서X = 중복X)
주어진 candidates 배열을 돌아가며 target이 되면 return 하도록 재귀함수로 구현했습니다

[SongI] 39. Combination Sum 풀이

---

Permutation&Combination/M-39-Combination Sum/JeongYe.js

주어진 배열 요소를 순회하면서 재귀를 이용해 풀었습니다. 
조합 내에서 같은 숫자로 이루어진 중복 조합을 방지하기 위해서  for문 돌때 마지막으로 선택한 인덱스부터 돌도록 구현했습니다.

39. Combination Sum 풀이

---

DP/M-300-Longest Increasing Subsequence/YoRim.cpp

300. Longest Increasing Subsequence 풀이

---

DP/M-300-Longest Increasing Subsequence/SongI.java

dp로 풀었습니다.
가장 긴 증가하는 부분수열 이라는 문제로 유명한 알고리즘 유형입니다.
d[i]라는 배열은 i번째까지 써서 만들 수 있는 가장 긴 수열의 길이 입니다.
dp로 풀면 이중 포문으로 O(n^2)로 풀수 있는데, 다른방법(이분탐색)으로도 풀수있다고 합니당
다른풀이 블로그 링크 : https://chanhuiseok.github.io/posts/algo-49/

[SongI] 300. Longest Increasing Subsequence 풀이

---

DP/M-146-LRU Cache/SongI.java

DP라고 분류했는데 전혀 다른 방법으로 풀었네요..! 
arrayList에 stack처럼 넣고 빼는 식으로 구현해봤는데, DP로 푸는 법도 올려볼게요

[SongI] 146. LRU Cache 풀이

---

DP/M-146-LRU Cache/JeongYe.js

- JS의 Map은 유일한 key 값을 가지고, 인서트된 순서를 기억한다는 점을 이용하였습니다. 
- get() 
- map에 key 값이 없다면 -1을  리턴 
- map에 key가 존재한다면, map에서 key를 제거하고 map에 다시 인서트한다. 
- put() 
- map에 key가 존재하면 제거
- map의 사이즈가 maxSize에 도달했다면, map의 첫번째 요소를 제거한다. 
- map에 (key,value) 쌍을 인서트한다. 
가장 적게 연산이 일어난 요소일수록 map의 앞쪽에 위치하기위해, get이나 put 연산이 일어나면 map에 새로 인서트를 하여서 구현하였습니다.

146. LRU Cache 풀이

---

Tree/M-96-Unique Binary Search Trees/SongI.java

이진검색트리라서 재귀로 순회하며 체크하는 방법을 처음에 생각했습니다.
그런데 디버깅하면서도 잘못된 점을 못찾았고 점점 산으로 가는 삽질을...하면서...
갯수를 구한다는 초점에 맞췄습니다.
n 개 노드의 이진트리 방법의 수는
root가 1에서 n이 될 수 있고, 루트는 왼쪽 서브트리와 오른쪽 서브트리로 나뉜다는 점을 이용했습니다. 
왼쪽 서브트리의 합과 오른쪽 서브트리의 합이 전체 트리의 방법의 수가 됩니다

[SongI] 96. Unique Binary Search Trees 풀이

---

Greedy/M-17-Letter Combinations of a Phone Number/SongI.java

알파벳을 String 배열에 넣어두고 풀었습니다.
1. 처음에 temp -> "a","b","c" 를 넣어두고
2. answer 배열에 temp를 전부 넣습니다. 그리고 temp를 초기화 합니다.
3. "d","e","f"를 더할 때 answer에 있는 문자열마다 더해줍니다.
4. digits 갯수만큼 반복합니다.
누적되는 string 값을 어떻게 구현하는지 물어보는 문제 같았습니다 ㅎ.ㅎ

[SongI]17. Letter Combinations of a Phone Number 풀이

---

Graph/H-128-Longest Consecutive Sequence/SongI.java
README.md

Arrays sort 로 정렬한 후 1씩 증가하는 구간인지 확인해서 풀었습니다.

[SongI]128. Longest Consecutive Sequence 풀이

---

Graph/H-128-Longest Consecutive Sequence/JeongYe.js

- JS의 Set 자료구조를 이용해서 nums 배열에 중복된 요소를 제거합니다. 
- 중복 제거된 nums를 순회하면서 연속된 숫자의 시작점을 찾습니다. 
- 시작점에서 length를 더한 숫자가 nums에 존재한다면 length를 +1 증가 시켜주면서, 연속된 숫자의 최대 길이를 찾습니다.

128. Longest Consecutive Sequence 풀이

---

DP/H-1306-Jump Game III/SongI.java

재귀로 풀었습니다.
bfs로도 풀 수 있을거같아요. 그래프 처럼 경우의 수를 따져 가지치기하면 됩니다 
(폴더는 dp 인데 문제에 적혀 있는 카테고리는 bfs, dfs, 재귀 더라구요 폴더 정리 날잡아서 해야겠어요 ㅎㅎㅎ)

[SongI] 1306. Jump Game III 풀이

---

DP/H-1306-Jump Game III/JeongYe.js

- DFS를 이용해서 풀었습니다. 
- 방문한 인덱스는 'visited'  값을 넣어주어 같은 인덱스로 경로가 반복되지 않도록 하였습니다.
- 다음 이동할 인덱스가 배열 범위를 벗어나거나, 이미 방문한 인덱스 일경우 `false`를 리턴하고, 배열 인덱스의 값이 0 이면 `true`를 리턴하도록 재귀함수를 구현했습니다.

1306. Jump Game III 풀이

---

0~100/M-11-Container With Most Water/JeongYe.js

- 영역의 너비는 두 지점 사이의 거리와 두 지점 중 낮은 높이를 곱한 값에 의해 결정됩니다. 
- 배열의 양 끝을 가리키는 변수를 이용해서, 좌우 인덱스를 배열 안쪽으로 이동하면서 area의 최대 값을 찾습니다.

11. Container With Most Water (TwoPointer) 풀이

---

101~200/M-148-Sort List/JeongYe.js

- mergeSort를 이용했습니다. 
- 연결리스트를 쪼갤 수 있을 때 까지  left, right 반으로 나누고 left, right의 시작점부터 값을 비교하면서, 오름차 순이 되도록 값을 스왑합니다. 
- 값 비교가 끝나면 포인터를 우측으로 한칸씩 이동하면서 left, right가 값이 없을 때까지 반복합니다.

[JeongYe] 148. Sort List 풀이

---

101~200/M-148-Sort List/SongI.java

O(nlogn) 으로 풀어야 하기 때문에 mergeSort 방법을 생각했습니다.  
ListNode가 LinkedList는 아니기 때문에 ListNode의 next를 포인터처럼 생각하고 풀었습니다. (이 과정에서 많이 헷갈렸습니다 ㅠ)
getMid() 메서드는 ListNode를 반으로 나누는 기능을 합니다

[SongI] 148. Sort List 풀이

---

901~1000/M-990-Satisfiability of Equality Equations/JeongYe.js

- a==b 와 같이 주어진 스트링을 파싱해서 (a,b) 처럼 map 구조에 부모 자식 관계를 표현했습니다. 
- a!=b 일경우 a의 부모와 b의 부모가 같다면 수식이 성립하지 않으므로 false를 리턴 하도록 구현했습니다. 
- 처음에 문자열 파싱할때 정규식을 사용하려했는데.. 자바스크립트에서는 
`const [a,start, , b] = "a==b"` 와 같이 식을 쓰면 스트링의 각 인덱스를 특정 변수에 넣을 수 있습니다!

[JeongYe] 990.Satisfiability of Equality Equations 풀이

---

0~100/M-22-Generate Parentheses/SongI.java

1. 브루트 포스로 ( 와 )로 만들 수 있는 문자열의 경우의 수를  찾습니다
2. 스택을 이용해 ( 와 ) 를 올바르게 정렬된 것을 찾아 반환 합니다
간단하게 보이는 풀이로 풀었는데 시간 절약하는 풀이가 있을 것 같습니다...ㅎㅎ

[SongI] 22. Generate Parentheses 풀이

---

201~300/M-213-House Robber II/JeongYe.js

저도 잘 이해가 가지 않아서 풀이의 도움을 받아 풀었습니다 ㅠㅠ 
우선 dp를 이용하였고, 처음부터 끝에서 2번째 집까지 털었을때와, 두번째 집에서 마지막 집까지 털었을때 2가지 경우의 수 중 최대 값을 반환합니다. 
dp[i]는 i 집을 털었을 때 얻을 수 있는 가장 큰 값을 가집니다. 
이전 집을 털었을 때와, 전전 집을 털었을 경우 현재 집도 털 수 있으므로 합한 값 중에 최대 값을 dp[i] 에 갱신해 줍니다.

[JeongYe] 213. House Robber II 풀이

---

201~300/M-213-House Robber II/SongI.java

오랜 고민 끝에 ㅠㅠㅠㅠㅠ 안풀려서 풀이를 봤습니다.... 근데 풀이도 이해하기 어렵더라구요 ㅠㅠ 
제가 이해한 것을 코멘트로 달아놓겠습니다

[SongI] 213. House Robber II 풀이

---

0~100/H-51-N-Queens/JeongYe.js

백트래킹을 이용하여서 퀸을 둘 수 있는 자리인지 검사하면서 수를 놓도록 하였습니다.  
재귀를 돌면서 n 만큼 행이 만들어졌을때 결과 배열에 푸쉬 하고,  board 배열은 퀸이 들어갈 열 인덱스 값을 가지고 있습니다.  `repeat` 함수를 이용해서 '.' 과 'Q'를 반복하는 스트링을 생성해서 결과 배열에 푸쉬하면 하나의 조합이 생성됩니다.

[JeongYe] 51. N-Queens 풀이

---

0~100/H-51-N-Queens/SongI.java

백트래킹을 이용한 대표 문제인데 요즘 재귀가 낯설어지는거 같아서 연습을 더 해야겠다고 느꼈습니다 ㅠㅠ
idx는 행이고 각 행마다 다른 열에 퀸을 놓아야 하기 때문에 isPossible로 퀸을 놓을 수 있는 자리인지 판별 한후 4개의 퀸을 구하면 String으로 만들어 업데이트 시켰습니다

[SongI] 51. N-Queens 풀이

---

301~400/M-338-Counting Bits/SongI.java

Integer의 bitCount를 이용해 풀었습니다.
https://ckdgus.tistory.com/38
비트마스킹 주요 식
1. 꽉찬 집합 : (1<<p) -1 
2. p 번에 원소 추가 : element |=(1<<p)
3. p 번 원소 가져오기 : element & (1<<p)
4. p 번 원소 0으로 바꾸기 : element &~(1<<p)
5. p번 왼쪽 원소 모두 0으로 바꾸기: element &=((1<<p)-1)
6. p번 오른쪽 모두 0으로 바꾸기 : element &=(-1<<p)
7. p번 원소 원하는 값 넣기 element&=~(1<<p)|((val?1:0<<p)
8. 원소 중 1인 개수 출력 Integer.bitCount(element)

[SongI] 338. Counting Bits 풀이

---

301~400/M-338-Counting Bits/JeongYe.js

10진수를 2진수로 변환하고, 문자열로 된 2진수 안에 1이 몇개있는지 카운팅해서 결과 배열에 넣도록 하였습니다. 
시간복잡도가 O(n^2) 이나 나와서 ㅠㅠ O(n)으로 푸는 방법을 생각해보겠습니다..

[JeongYe] 338. Counting Bits 풀이

---

301~400/H-329-Longest Increasing Path in a Matrix/SongI.java

matrix에서 갈 수 있는 4 방향을 탐색하는데 자기보다 작은 것을 큐에 넣습니다. 큐에서 빼면서 탐색한 길이 최댓값을 저장하는 d[] 배열에 최댓값을 갱신합니다.

329. Longest Increasing Path in a Matrix 풀이

---

601~700/M-695-MaxAreaOfIsland/SongI.java

bfs 로 풀었습니다 :)
bfs 메서드는 한 섬의블롯 갯수를 구하는 메서드 입니다

[SongI] 695. Max Area of Island 풀이

---

101~200/M-105-ConstructBinaryTreeFromPreorderandInorderTraversal/SongI.java

preorder, inorder 순서 규칙을 찾아서 재귀로 구현했습니다 !

[SongI] 105. Construct Binary Tree from Preorder and Inorder Traversal 풀이

---

101~200/M-105-ConstructBinaryTreeFromPreorderandInorderTraversal/JeongYe.js

- 전위 순회와 중위 순회에서 루트를 탐색하는 순서를 이용하여서 풀었습니다. 
- 전위 순회는 `root` -> left -> right , 중위 순회는 left -> `root` -> right 순으로 탐색합니다. 
- 전위 순회 목록을 가지고 노드별 배열 인덱스 값을 map 에 저장합니다.
- 전위 순회에서 첫 번째 항목인 루트를 가져옵니다. 
- 루트의 인덱스를 기준으로 전위 순회 목록에서 좌,우 반 씩 쪼개어 서브 트리를 형성합니다. 
- 위 과정을 반복합니다.

[JeongYe] 105. Construct Binary Tree from Preorder and Inorder Traversal 풀이

---

0~100/M-3-LongestSubstringWithoutRepeatingCharacters/SongI.java

* logN
* set으로 중복된 글자를 찾습니다. 
* sb에는 이어지는 글자들을 기록합니다 
* 만들어지는 sb들중에 가장 긴 값을 max 로 기록합니다

[SongI] 3. Longest Substring Without Repeating Characters 풀이

---

0~100/M-3-LongestSubstringWithoutRepeatingCharacters/JeongYe.js

- 부분 문자열의 시작 인덱스를 가리키는 `start` 변수를 생성한다. 
- 문자열 길이 만큼 for문을 돌면서 i번 인덱스가 map에 존재하는지 확인한다. 
- 이미 map에 등록된 문자라면, 문자열 시작 인덱스를 우측으로 한 칸 증가 시킨다. 
- map에는 현재 인덱스의 문자와, 인덱스 쌍을 저장한다. 
- `현재 인덱스 - 문자열 시작 인덱스 + 1` 값이 문자열의 길이가 된다. 최대 값으로 갱신한다.

[JeongYe] 3. Longest Substring Without Repeating Characters 풀이

---

101~200/M-153-Find Minimum in Rotated Sorted Array/JeongYe.js

- 시간복잡도를 O(logN) 으로 풀어야하고 정렬된 배열이 주어져서 이분탐색 하는 방법을 선택했습니다. 
- 순환된 배열 안에서 값이 증감하는 구간을 찾는게 포인트입니다! 
- 예) 4 5 6 (7 1) 2 
- 배열의 좌, 우 인덱스를 가리키는 start, end 포인터를 사용합니다. 
- 배열의 중간 인덱스를 찾습니다. `mid = (start + end) / 2` 
- 현재 mid 인덱스가 증감 구간인지 확인합니다. 
- 배열의 첫번째 요소보다 nums[mid] 값이 크다면, start 인덱스를 mid +1 로 이동하여 우측을 탐색합니다. 
- 아니라면, 배열의 왼쪽을 탐색해야 하므로 end 인덱스를 mid -1로 이동합니다.   
- start 인덱스가 end보다 작거나 같아질 때 까지 반복합니다.

[JeongYe] 153. Find Minimum in Rotated Sorted Array 풀이

---

101~200/M-187-Repeated DNA Sequences/SongI.java

0부터 문자열길이-10 (구하는 문자열의 길이가10이므로 10을 뺌) 의 순서로 문자열 index 를 탐색하면서
구한 10글자 문자열을 HashMap의 Key로 저장하고, 횟수도 구합니다. 
그중 2번 이상 나온 문자열을 answer 리스트에 저장해서 반환합니다.

[SongI] 187. Repeated DNA Sequences 풀이

---

101~200/M-187-Repeated DNA Sequences/JeongYe.js

- 0번 인덱스 부터 문자열의 길이가 10이 되도록 자릅니다. 
- Set을 이용하여 이미 마주친 문자열인지 중복 검사를 합니다.

[JeongYe] 187. Repeated DNA Sequences 풀이

---

601~700/M-687-Longest Univalue Path/SongI.java

왼쪽, 오른쪽 노드로 dfs 하면서 길이를 구합니다
현재노드(root)값과 자식들의 값을 비교해서 같으면 길이에 +1 을 추가하고 
오른쪽과 왼쪽 값의 최대값과 answer 와 l+r을 비교해 최대값을 비교합니다.
저는 이부분에서 좀 헤맸는데, 왼쪽-root-오른쪽 이었을 때의 길이와
왼쪽-root 또는 root-오른쪽 의 길이를 비교해서 최대 max값을 구해야 하기 때문에 return 값으로 넘겨주지 않는 게 포인트인 것같습니다

[SongI] 687. Longest Univalue Path 풀이

---

101~200/E-122-Best Time to Buy and Sell Stock II/JeongYe.js

전에 비슷한 유형의 문제를 푼 적이 있었는데요, 이 문제는 사고파는 순서가 정해져 있고 여러 번 사고 파는 과정을 할 수 있다는 점이 달랐네요..! 
처음에 2중 for 문을 사용해서 완전 탐색을 할까 하다가 시간복잡도가 너무 커질 거 같아서 다른 방법으로 풀었습니다.. 
오늘 가격과 어제의 가격을 비교해서, 어제보다 오늘 가격이 더 뛰었다면 주식을 바로 팔아서 이익을 누적시키면 됩니다. 
문제 난이도 치고 고민을 많이 한 문제 같아요..ㅠㅠ 
릿코드에 주식 사고파는 시리즈 문제가 여러 개 있던데 다음에는 좀 더 응용시키는 문제를 풀어보고 싶네여!! 
medium으로 가져와 볼게요!

[JeongYe] 122. Best Time to Buy and Sell Stock II 풀이

---

101~200/E-122-Best Time to Buy and Sell Stock II/SongI.java

easy 가 아닌 문제 같았어요... 처음에 너무 복잡하게 생각했는지 헤맸습니다ㅠ
뒤에 오는 수가 더 커야지 이득을 보기 때문에 prices[i]>prices[i-1] 를 체크합니다. 
거래가 일어나는 조건이 정해져 있기 때문에 (You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times)., You may not engage in multiple transactions simultaneously (i.e., you must sell the stock before you buy again).)  해당 풀이가 가능한 거 같아요
사실 아직도 거래(주식을 사고 팔고까지)가 일어나는 조건은 잘 이해가 안되네여....

[SongI] 122. Best Time to Buy and Sell Stock II 풀이

---

101~200/M-131-Palindrome Partitioning/SongI.java

전형적인 재귀 문제였어요ㅎㅎ 
펠린드롬일때만 계속 탐색하고 펠린드롬 문자열을 구하면 됩니당 👍

[SongI] 131. Palindrome Partitioning 풀이

---

101~200/M-131-Palindrome Partitioning/JeongYe.js

백트래킹을 써서 풀었습니다! 
풀이하면서 삽질한 부분은 partition 하는게 주어진 문자열에서 1, 2, 3 항상 균등한 길이로 쪼개는 것으로 이해해서 이상하게 풀고 있었네요..! 예를 들어서 aaba 라는 문자열이 주어지면 레벨1에서는 (a), (a), (b) , (a) 레벨2에서는 (aa) (ba) 이런 방식으로만 쪼개진다고 생각했네요 ㅠㅠ 
- 제가 사용한 방법은 백트래킹 함수에 시작 인덱스, [] 배열을 인수로 받습니다. 
- 시작 인덱스를 끝 인덱스 값으로 초기화하고, 시작 인덱스 부터 끝 인덱스까지 문자열을 잘라서 팰린드롬인지 검사합니다. 
- 팰린드롬이면 자른 부분 문자열을 배열에 넣고 백트래킹을 진행합니다. 
- start 인덱스가 전체 문자열의 길이보다 커지면, 현재 배열에 있는 문자열을 결과 배열에 넣고 리턴합니다.

[JeongYe] 131. Palindrome Partitioning 풀이

---

400~500/M-402-Remove K Digits/JeongYe.js

K만큼 지워서 큰 숫자 만드는 문제랑 비슷해 보여서 최대한 응용해서 풀었습니다..! 
스택의 top 보다 현재 숫자가 크면 무조건 스택에 푸쉬하고, 
스택의 top이 현재 숫자보다 크면 현재 숫자보다 큰 수들을 모두 stack에서 제거해줍니다. (K 가 0 보다 클때만) 
만약 k 가 남아 있는 경우, 뒤에서부터 k만큼 제거해줍니다. 
처음에 문자열 앞에 "0020" 의 0 을 어떻게 제거 해줄까 하다가.. string을 그냥 number로 변환시켜 버렸는데 문자열이 많이 길어지면 number 범위를 초과해버려서 ㅠㅠ 안되더라구요 
그래서 스택의 top이 0 이면서 길이가 1 이면 스택에서 무조건 제거 해버리도록 구현했습니다.

[JeongYe] 402. Remove K Digits 풀이

---

400~500/M-402-Remove K Digits/SongI.java

그리디 문제.. 너무 어려워요 ㅠㅠㅠㅠㅠ
풀다가 답이 안나와서 discussion에 있는 풀이중 하나를 참고 했습니다 ;ㅅ;

[SongI] 402. Remove K Digits 풀이

---

201~300/M-240-Search a 2D Matrix II/JeongYe.js

행과 열이 모두 오름차순으로 정렬되어 있다는 점을 이용합니다! 
첫번째 행의 가장 끝 열부터 탐색하면서,  목표 값이 현재 행에 없으면 행을 하나 증가 시켜줍니다. 
현재 위치 보다 목표 값이 더 작다면, 열을 하나 감소 시켜줘서 더 작은 값을 탐색 하도록 합니다. 
처음에 목표 값이 행에 존재하는지 검사하고 열을 찾을땐 이진탐색....을 이용했는데 시간이 넘 오래걸려서 다른 분들 풀이 구경하다가 참고했습니다!! 신기한 방법이네요 시간이 대략 8배나 줄었어요

[JeongYe] 240. Search a 2D Matrix II

---

201~300/M-240-Search a 2D Matrix II/SongI.java

생각보다 간단하게? 풀었어요
가로 세로에서 target 보다 큰것을 제외하고 탐색을 돌면 찾는 로직입니다 :3

[SongI] 240. Search a 2D Matrix II 풀이 

---

0~100/M-55-Jump Game/SongI.java

dp 로 풀었습니다 
nums[i]+i 현재 점프할 수 있는 값, d[i-1] 이전까지의 최대값을 구하면 됩니다

[SongI] 55. Jump Game 풀이

---

0~100/M-55-Jump Game/JeongYe.js

현재 인덱스에서 이동할 수 있는 횟수를 이용했습니다!
한 칸 이동할 때 마다 move를 1씩 감소 시키고 현재 위치를 하나 증가 시켜줍니다. 
이동 횟수 move를 다 사용할 때 까지 마지막 인덱스에 도달하지 못하면 while문을 빠져나오면서 false를 리턴하고, 
만약에 현재 위치가 마지막 인덱스까지 도달한 경우라면 true를 반환 하도록 했습니다.

[JeongYe] 55. Jump Game 풀이

---

101~200/M-109-Convert Sorted List to Binary Search Tree/JeongYe.js

연결 리스트가 오름차순으로 정렬 되어있다는 점을 이용했습니다. 
리스트를 중간 지점 기준으로 분할해서, 재귀를 통해 왼쪽 서브트리 생성하고, 오른쪽 서브트리를 생성하는 방식으로 풀었습니다!

[JeongYe] 109. Convert Sorted List to Binary Search Tree

---

101~200/M-109-Convert Sorted List to Binary Search Tree/SongI.java

증가하는 수가 담긴 linkedList를 tree로 변환하는 문제인데, 트리로 바꾸는 과정에서 순서를 어떻게 정해야 하는지 문제의 예시를 보고는 이해가 가지 않아서 풀이를 참고했습니다ㅠ^ㅠ
분할 정복처럼 푸는데, 앞의 노드와 뒤의 노드를 분리해서 각각 left, right로 재귀호출을 하여 분리되지 않을 때 앞의 노드를 먼저 출력하게 됩니다 :)

[SongI] 109. Convert Sorted List to Binary Search Tree 풀이

---

1700~1800/M-1737-Change Minimum Characters to Satisfy One of Three Conditions/JeongYe.js

문제가 뭘 요구하는지..? 뜻이 너무 이해가 안가서... 풀이 보고 풀었습니다ㅠㅠ
문제에서 만족해야 하는 조건 3개중 1,2번은 비슷한 유형이여서 operation1 이라는 함수에서 파라미터만 바꿔서 처리하고,  조건3번은 operation2 에서 처리합니다. 
주어진 문자열 a,b를 각각 조건1~3에 맞게 처리했을 때 나올 수 있는 연산 수의 최소 값을 구하면 됩니다!

[JeongYe] 1737. Change Minimum Characters to Satisfy One of Three Conditions 풀이

---

1700~1800/M-1737-Change Minimum Characters to Satisfy One of Three Conditions/SongI.java

사실 솔루션을 참고해서 풀었습니다 ㅎ.ㅎ;
처음에 a,b 두 문자에 대해서 hashmap 으로 만들고 교집합 차집합으로 구하면 되지 않을까? 했는데
생각보다 구현이 복잡해져서 다른 풀이를 찾으려고 했어요, 그러다 생각이 안나서 솔루션의 도움을 받았습니당 ㅠ.ㅠ

[SongI] 1737. Change Minimum Characters to Satisfy One of Three Conditions 풀이

---

0~100/M-5-Longest Palindromic Substring/JeongYe.js

dp로 푸는 방법이 있다고 하네용. 저는 dp 대신 다른 방법을 이용했습니다! 
먼저 스트링의 각 인덱스를 순회합니다. 
각 인덱스를 중심으로 삼아서 좌우로 퍼져나가듯이 start, end 인덱스를 감소/증가 시키면서, 가장 긴 팰린드롬을 찾아서 갱신하는 방법입니다! 
저희 벌써 40문제를 향해 달려가고있네여,, 화이팅!!! 👍😎

[JeongYe] 5. Longest Panlindromic Substring 풀이

---

0~100/M-5-Longest Palindromic Substring/SongI.java

펠린드롬 문제로 글자길이에 따라 펠린드롬이 될수 있는 걸 찾아서 풀었습니당

[SongI] 5. Longest Palindromic Substring 풀이

---

701~800/M-714-Best Time to Buy and Sell Stock with Transaction Fee/SongI.java

사담이지만, 아.. 요즘 알고리즘 슬럼프...? 실력이 안늘고 머리가 자꾸 굳어가는 느낌이 드네요 ㅠㅠ 
해당 문제는 dp 일거라 생각을 하고  풀이를 시작했는데 dp[살때 인덱스][팔때 인덱스] 2차원 배열을 생각했어요... 그리고 점점 복잡해져 가다가 풀이를 포기하고 솔루션을 슬쩍 봤습니다 ㅎ.ㅎ...  ㅠㅠㅠㅠ좌절...
이번 풀이의 코드는 
1. 한번의 거래가 발생할때 최댓값을 prev로 판단합니다 
2. answer 변수는 주식을 사고 팔았을때의 최대 수익입니다
3. 즉 prve 에서 주식을 어느인덱스에서 살지 정하고 answer에서 언제 팔지 정합니다 :)

[SongI] 714. Best Time to Buy and Sell Stock with Transaction Fee 풀이

---

701~800/M-714-Best Time to Buy and Sell Stock with Transaction Fee/JeongYe.js

풀고 싶은 방법이 있었는데 코드 작성하다가 계속 막혀서.. 풀이의 도움을 받아 다른 방법으로 풀었습니다 ㅠㅠ 
처음에 생각한 방법은, 
dp를 이용해서 i일에 구매하고 더 큰 수익을 얻을 수 있는 날에 판매 하고, 
판매일 다음 날 부터 다시 buy -> sell 과정을 반복 하면 i일에 주식을 구매했을 때 최대 수익을 구할 수 있지 않을까? 하고 이 방법을 생각했습니다! 근데 코드 짜다가 너무 막혀서 ㅠㅠ 다른 방법을 선택했습니다 
--- 
제가 참고한 방법은, i=1 부터 끝까지 루프를 돌면서 i일에 `판매할 경우/구매할 경우`에 대해 `최대 수익을 갱신`하는 방법입니다. 
갱신하는 로직은 두가지로 나눌 수 있습니다. 
- i일에 **구매**할 경우 
- `i-1일 에 구매`했을 때 수익과, `i-1일 에 판매하고 i일에 구매`했을 때 수익 중 최대 값으로 갱신한다. 
- i일에 **판매**할 경우 
- `i-1일 에 판매` 했을 때 수익과, `i-1일에 구매하고 i일에 판매` 했을 때 수익 중 최대 값으로 갱신한다. 
위 과정을 거치면 수익의 최대 값은 sell 배열의 마지막 인덱스에 저장 됩니다!

[JeongYe] 714. Best Time to Buy and Sell Stock with Transaction Fee 풀이

---

501~600/M-528-Random Pick with Weight/JeongYe.js

문제 정의가 상당히 애매한 문제였네요.. randomPick() 함수가 정확히 무슨 기능을 하는지 저만 헷갈렸나요..?😭 
처음에 이해한대로 풀이한 방법은 w배열의 인덱스 중 랜덤하게 뽑아서 `w[i] / sum(w)` 수식을 적용해서 pickIndex() 함수에서 리턴해주도록 하였습니다. 
근데 다른 테스트 케이스 에서 자꾸 실패가 나더라구요.. 게시판 구경하다가 문제 정의에 대해서 잘 정의된 글이 있어서 참고했어요! [(🔗링크)](https://leetcode.com/problems/random-pick-with-weight/discuss/671445/Question-explained)

[JeongYe] 528. Random Pick with Weight 풀이

---

501~600/M-528-Random Pick with Weight/SongI.java

어떤 배열에서 어떤 인덱스가 나올 확률을 구하는 방법이 문제에 나와있어서 그대로 쓰면 되긴 하는데 문제는 ```pickIndex``` 함수 엿던거 같아요 ;ㅁ;
저는 해답을 보고 풀었는데 ㅠ.ㅠ... 이진탐색으로 랜덤하게 찾는다는게 사실 잘 이해가 가질 않았어요...다시 한번 풀어봐야할 것 같아요 저는 ㅠㅠ

[SongI] 528. Random Pick with Weight 풀이

---

201~300/M-208-Implement Trie/SongI.java

트라이 자료구조에 대해서 공부해보려고 이 문제를 뽑았는데 ㅎ..ㅎ 답안은 풀이를 봤습니다..!

[SongI] 208. Implement Trie (Prefix Tree) 풀이

---

201~300/M-208-Implement Trie/JeongYe.js

예~~전에 코딩테스트 볼 때 Trie 쓰는 문제가 나왔었는데 이게 뭐지? 했는데 드디어 풀어보네여..!!! 
이번 문제 풀기전에 간단하게 Trie에 대해서 이해하기 위해서 
https://www.youtube.com/watch?v=7XmS8McW_1U&t=200s&ab_channel=freeCodeCamp.org 동영상을 참고했습니다! 
JavaScript로 설명되어 있지만 그림이랑 같이 나와서 이해하기 좋았어요! 
주어진 단어의 한 문자를 관리하기 위한 `Node` 클래스, 트라이 자료구조를 구현한 `Trie` 클래스가 있습니다. 
`Node` 클래스는 `keys` 라는 프로퍼티를 가지고 있는데, 현재 문자열을 키 값으로 가지고 현재 문자열 이후의 단어가 `Node` 로 이어져 있는 구조입니다. 
클래스에 대한 상세 설명은 주석에 달아 놓았습니다 😀

[JeongYe] 208. Implement Trie 풀이

---

301~400/M-378-Kth Smallest Element in a Sorted Matrix/JeongYe.js

`이진 탐색`을 이용해서 2차원 배열에서 k번째 작은 원소를 찾으면 됩니다! 
이 문제는 행과 열이 모두 오름차순으로 정렬되어 있는데요, 정확하게 중간 숫자의 인덱스 찾는 것이 어렵습니다. 그래서 시작 숫자와 마지막 숫자의 범위를 이용해서 중간 숫자를 찾아 탐색 범위를 좁혀 나가는게 포인트 입니다!

[JeongYe] 378. Kth Smallest Element in a Sorted Matrix

---

301~400/M-378-Kth Smallest Element in a Sorted Matrix/SongI.java

간단하게? 풀었어요 ㅎ.ㅎ 1차원 배열에 몰아넣고, 1차원 배열을 Sort 시켜서 k-1번째를 찾았습니다!

[SongI] 378. Kth Smallest Element in a Sorted Matrix 풀이

---

901~1000/M-934-Shortest Bridge/SongI.java

늦었네요! ㅠㅠㅎㅎㅎ
생각보다 풀이 시간이 길었던 문제에요 휴...ㅠ
bfs를 이용해서 풀었는데 두가지 섬으로 나뉘기 때문에 하나의 섬을 먼저 2로 만들어 주며 체크를 합니다
다음에 2번 섬에서 끝부분?(0과 만나는 2)를 큐에 넣고 그 위치에서 다른 1번 섬에 도착하기 까지 최소 거리를 구하면 됩니다!

[SongI] 934. Shortest Bridge 풀이

---

901~1000/M-934-Shortest Bridge/JeongYe.js

초콤 늦었네용..ㅎㅎㅎ죄송해요😭
먼저 섬의 시작점 '1' 을 찾아서 시작점을 기준으로 사분면을 탐색합니다. 
사분면을 탐색하면서 섬으로 이어질 가능성이 있는(?) 1이 아닌 지점들을 다 큐에 넣어줍니다. 
큐에서 지점을 하나하나 방문하면서 '#'으로 방문 처리를 해주고, 섬의 다른끝 지점 '1' 을 만나면 섬을 잇는데 flip한 비용을 리턴해주면 됩니당!

[JeongYe] 934. Shortest Bridge 풀이
